import React from "react";
import Navbar from "./Navbar";
const Help = () => {
  return (
    <>
      <Navbar></Navbar>
      <div>
        The website is designed in order to manage the diamond poloshing
        factory. The system has three Roles : 1.Owner 2.Manager 3.Worker In
        System the worker only has viewing permissions of his/her own work done.
        The worker can see on which date how much work he/she has done and how
        much money they have earned. The Manager have all the CRUD
        operations.Manager can add new workers,fire/ remove workers ,can assign
        work to workers and can update the work done by the workers on any
        particular day. Otherthan this Manager can generate the reports of all
        profits and losses of the factory at the end of the month for the owner.
        The owner has real and update permissions. owner can see the report
        generated by the manager and can add/remove the manager as he needed.
      </div>
    </>
  );
};

export default Help;
